{% set name = "ciso8601" %}
{% set version = "2.3.1" %}
{% set sha256 = "3212c7ffe5d8080270548b5f2692ffd2039683b6628a8d2ad456122cc5793c4c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ciso8601

about:
  home: https://github.com/closeio/ciso8601
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast ISO8601 date time parser for Python written in C

  description: |
    ciso8601 converts ISO8601 date time strings into Python datetime objects.
  dev_url: https://github.com/closeio/ciso8601

extra:
  recipe-maintainers:
    - synapticarbors
